In [ ]:
from google.colab import files
uploaded = files.upload()
print(uploaded)
import pandas as pd
df = pd.read_csv('team_stats.csv')

Saving team_stats.csv to team_stats.csv

In [ ]:
df = df.rename(columns={
    "Season": "season",
    "HomeTeam": "home",
    "AwayTeam": "away",
    "FullTimeHomeGoals": "homegoals",
    "FullTimeAwayGoals": "awaygoals",
    "FullTimeResult": "result",
    "HomeShots": "homeshots",
    "AwayShots": "awayshots",
    "HomeShotsOnTarget": "homeshotstarget",
    "AwayShotsOnTarget": "awayshotstarget",
    "HomeYellowCards": "homeyellow",
    "AwayYellowCards": "awayyellow",
    "HomeRedCards": "homered",
    "AwayRedCards": "awayred"
})

In [ ]:
home = df[['season','home','homegoals','awaygoals','result']].copy()
home.columns = ['season','team','goalwin','goallose','result']
home['points']=home['result'].map({'H': 3, 'A':0 , 'D':1})

away = df[['season','away','awaygoals','homegoals','result']].copy()
away.columns = ['season','team','goalswin','goallose','result']
away['points']= home['result'].map({'H':0 , 'D': 1 , 'A': 3 })

gopbang = pd.concat([home,away],ignore_index = True)

gopbang.groupby(['season','team']).agg({'points':'sum'}).reset_index().sort_values('points',ascending = False)

     season              team  points
31  2024/25         Liverpool      82
20  2024/25           Arsenal      67
32  2024/25          Man City      64
34  2024/25         Newcastle      63
25  2024/25           Chelsea      63
35  2024/25     Nott'm Forest      61
21  2024/25       Aston Villa      60
22  2024/25       Bournemouth      53
24  2024/25          Brighton      52
23  2024/25         Brentford      52
12  2023/24          Man City      51
28  2024/25            Fulham      51
0   2023/24           Arsenal      49
26  2024/25    Crystal Palace      46
39  2024/25            Wolves      41
10  2023/24         Liverpool      40
27  2024/25           Everton      39
33  2024/25        Man United      39
37  2024/25         Tottenham      38
38  2024/25          West Ham      37
6   2023/24           Chelsea      35
14  2023/24         Newcastle      31
13  2023/24        Man United      29
7   2023/24    Crystal Palace      28
17  2023/24         Tottenham      27
1   2023/24       Aston Villa      26
9   2023/24            Fulham      23
2   2023/24       Bournemouth      23
29  2024/25           Ipswich      22
8   2023/24           Everton      22
30  2024/25         Leicester      21
3   2023/24         Brentford      20
18  2023/24          West Ham      19
4   2023/24          Brighton      18
19  2023/24            Wolves      18
15  2023/24     Nott'm Forest      16
5   2023/24           Burnley      13
11  2023/24             Luton      11
36  2024/25       Southampton      11
16  2023/24  Sheffield United       7

In [ ]:
hieusuat = ( df.groupby(['season'], as_index = False).agg({ 'homeshots':'sum',
                                                           'awayshots':'sum',
                                                            'homeshotstarget':'sum',
                                                            'awayshotstarget':'sum'}))
hieusuat['hieusuatnha']= hieusuat['homeshotstarget'] /hieusuat['homeshots']
hieusuat['hieusuatkhach']= hieusuat['awayshotstarget']/hieusuat['awayshots']
hieusuat[['season','hieusuatnha','hieusuatkhach']]

    season  hieusuatnha  hieusuatkhach
0  2023/24     0.356396       0.375326
1  2024/25     0.351452       0.349788

In [ ]:
tong_the = (
  pd.concat([
    df[['home','homeyellow','homered']].rename( columns={'home' : 'team', 'homeyellow': 'yellow', 'homered': 'red'}),
    df[['away','awayyellow','awayred']].rename( columns ={'away' : 'team', 'awayyellow': 'yellow', 'awayred': 'red'})
  ]).groupby(['team'], as_index = True)[['yellow','red']].mean()
     .rename(columns={'yellow':'yellow_mean','red':'red_mean'})

)
tong_the.sort_values('yellow_mean', ascending=False).head(100).reset_index()

                team  yellow_mean  red_mean
0            Chelsea     2.584906  0.037736
1        Bournemouth     2.481481  0.074074
2        Southampton     2.457143  0.085714
3            Ipswich     2.314286  0.142857
4          Leicester     2.314286  0.000000
5             Wolves     2.207547  0.056604
6            Everton     2.094340  0.037736
7      Nott'm Forest     2.037736  0.037736
8         Man United     2.037736  0.056604
9             Fulham     2.037736  0.056604
10          Brighton     2.000000  0.074074
11    Crystal Palace     1.981132  0.094340
12       Aston Villa     1.981132  0.056604
13  Sheffield United     1.888889  0.166667
14          West Ham     1.888889  0.092593
15         Tottenham     1.886792  0.018868
16             Luton     1.842105  0.000000
17         Brentford     1.833333  0.037037
18           Burnley     1.833333  0.166667
19         Liverpool     1.740741  0.055556
20           Arsenal     1.735849  0.094340
21         Newcastle     1.685185  0.037037
22          Man City     1.370370  0.018519

In [ ]:
homee = df.copy()
homee['win']= (homee['result']=='H').astype(int)
homewinrate = homee.groupby('home')['win'].mean().reset_index()
homewinrate.rename(columns={'home': 'team', 'win': 'winhome'}, inplace=True)

awayy = df.copy()
awayy['win']=(awayy['result']=='A').astype(int)
awaywinrate = awayy.groupby('away')['win'].mean().reset_index()
awaywinrate.rename(columns={'away': 'team', 'win': 'winaway'}, inplace=True)

winrate = pd.merge(homewinrate, awaywinrate, on='team', how='outer').fillna(0)

winrate.head(10)

             team   winhome   winaway
0         Arsenal  0.666667  0.615385
1     Aston Villa  0.481481  0.423077
2     Bournemouth  0.407407  0.333333
3       Brentford  0.407407  0.333333
4        Brighton  0.370370  0.259259
5         Burnley  0.111111  0.111111
6         Chelsea  0.666667  0.384615
7  Crystal Palace  0.407407  0.307692
8         Everton  0.333333  0.153846
9          Fulham  0.384615  0.370370

In [16]:
df['homedraw'] = df['result'].map({'H': 0, 'D': 1, 'A': 0})
df['awaydraw'] = df['result'].map({'H': 0, 'D': 1, 'A': 0})

HomeDraw = df.groupby(['season','home'])['homedraw'].sum()
AwayDraw = df.groupby(['season','away'])['awaydraw'].sum()

TotalDraw = HomeDraw.add(AwayDraw, fill_value=0).reset_index()
TotalDraw.columns = ['season','team','totaldraw']

MaxDraw = TotalDraw.groupby('season')['totaldraw'].max().reset_index()
MaxDraw.columns = ['season','maxdraw']

Result = TotalDraw.merge(MaxDraw, on='season')
print(Result[Result['totaldraw'] == Result['maxdraw']].sort_values(['season','totaldraw'], ascending=[False,False]))

     season      team  totaldraw  maxdraw
27  2024/25   Everton         15       15
5   2023/24   Burnley          7        7
8   2023/24   Everton          7        7
18  2023/24  West Ham          7        7